// Autogenerated helper to use numbered card images (1.png ... 104.png).
// Place this file in: src/assets/cards/index.ts
// Put all PNGs (1.png ... 104.png) in the same folder.
//
// Usage example:
//   import { getCardSrc } from './src/assets/cards';
//   <img src={getCardSrc(55)} alt="Card 55" />
//
export const getCardSrc = (n: number) => new URL(`./${n}.png`, import.meta.url).href;

// Optional: pre-validated list of available ids
export const ALL_CARD_IDS = Array.from({ length: 104 }, (_, i) => i + 1);
